version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: football-team-management-db
    environment:
      MYSQL_DATABASE: football_team_management
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: football-team-management-app
    depends_on:
      - database
    volumes:
      - .:/var/www/html
    networks:
      - app_network
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
